//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Input/MenuActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MenuActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MenuActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MenuActions"",
    ""maps"": [
        {
            ""name"": ""Always"",
            ""id"": ""6fffd7ed-3092-4be6-92fd-2c24b5e0a437"",
            ""actions"": [
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""931a205c-afdd-4e6f-8bf4-8feb7669f63b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6f923dae-da83-41f3-a150-c5562211350b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""c36d3fbc-b23e-4a26-b5d0-cec39c46e892"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""8c935222-0269-48d7-b45c-f01a9a9b564f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""b5a96a68-7d22-4b33-8bf4-700f9b75ee63"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action1"",
                    ""type"": ""Button"",
                    ""id"": ""9e99bf61-40a1-4b20-ad2d-80f5323c76d0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action2"",
                    ""type"": ""Button"",
                    ""id"": ""8707be83-d94f-4d19-8ce0-8d740798edcb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action3"",
                    ""type"": ""Button"",
                    ""id"": ""9c76f15e-7d93-4daf-93a1-f574464fab8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action4"",
                    ""type"": ""Button"",
                    ""id"": ""c84bb327-eb79-4aa1-91e7-8476d5b296dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TabLeft"",
                    ""type"": ""Button"",
                    ""id"": ""2c01ab11-c189-46a1-a314-29ff40d9863e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TabRight"",
                    ""type"": ""Button"",
                    ""id"": ""1153ea0c-801e-4311-8211-6b97b0476a95"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SubTabLeft"",
                    ""type"": ""Button"",
                    ""id"": ""7f8faf6f-0a20-47d2-9f31-3b3c31ee363e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SubTabRight"",
                    ""type"": ""Button"",
                    ""id"": ""dcc0fe70-ecc7-4f00-9b6c-737e9a5a3ad5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveLeft"",
                    ""type"": ""Button"",
                    ""id"": ""44461c2e-ddbd-4318-80a7-abbe9222fc50"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveRight"",
                    ""type"": ""Button"",
                    ""id"": ""660ee0e5-07d4-4987-97a4-f40e31d17051"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenMenu"",
                    ""type"": ""Button"",
                    ""id"": ""25308b97-4c89-4581-b2cb-ecc87694b64c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenSecondaryMenu"",
                    ""type"": ""Button"",
                    ""id"": ""f9df2c02-1f32-4a64-998f-37dfb6a3c136"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f38ab50a-a7ce-439f-8931-4a407a66e6e6"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fbf31c95-541f-4a87-b0bc-075756941fcf"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone(min=0.9)"",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""820fc7b1-f3a7-4467-af13-f19bb3b310bc"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e327df63-1072-4578-a285-9bf934729f39"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""003de796-fb97-4710-b75c-c65bf6258440"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c7552365-3c6e-4f00-82c0-9763ee57a217"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""945a6431-ff47-47a6-9e01-55a88329fc75"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""5aacb0f6-204a-45c9-a3df-74df3be28028"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""46b54212-35f4-4ccd-bf0f-a8c64950101e"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""aadffb17-6b2e-468e-b31d-ee3fa02a49cd"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""04d9d5a5-6a2e-4e2a-b1c2-8e6112284cd3"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d1e3ec70-ba34-49f2-88d3-845a19fce8ee"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""de0765f4-5f7b-4294-a368-31b8feb58473"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1de2df15-2a53-4e28-b7de-f160c91cd0d8"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a284576-16c2-411c-ac11-6fe8886f3d04"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b53cf06-2071-4235-a7f1-4ba7d5bbcb26"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1dbdb4d1-81c8-431c-8ecc-1e6bba60e53b"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d2e2060b-4f09-431c-971a-99dad45d2ec3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9b98785-010f-48c8-8f89-7784370b77f1"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubTabRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81ae8254-f7d6-4859-b69e-8496a9ec50df"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubTabRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e81fe691-96be-4c8a-8896-62ca9ebbc43e"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f8900a3-56e2-46a6-a8dd-2d064f5067f1"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""166572bc-cbe4-4806-b10f-f4d422a1639b"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7733eb82-a24d-4ca1-af16-870dc004bc81"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""263f24ce-95f1-4e0e-ad01-564e9f6db694"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c9b29f2-18ae-4b3e-a360-e8c9fbe1c88f"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5916e7c8-8e83-4b8e-b00d-deeac5090241"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32679f5b-e137-4474-b2e8-2cc790d2183c"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89a4391c-381b-4785-95b2-e6762cc79bc0"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2700a34-8312-4d26-9046-16f663e610d2"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TabRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3eaf41f7-5db6-4950-98b8-660ddc6bd268"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TabRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""454c3526-79d6-4cca-acd0-846c0e1e4116"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TabLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da7bdae1-6b51-497d-9c55-e7878d71254e"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TabLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7a62855-8510-46ec-8db8-1b0c50a5fbb1"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubTabLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2d41d6a-32e0-4a33-a586-d552c9cb2bfc"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubTabLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1a9d568-08b0-49ab-94f9-08a55897e0c5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72e6ca7d-c6ea-4c76-9ecc-3000dc2de840"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e1e179f-752d-4e37-8432-cf44f1bc4a8a"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""714eb972-c5e6-4802-a3e5-e2a6fa61a0af"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""629137a9-3527-4d60-9405-cd97543028fe"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02262ab8-7d0d-48bc-a668-e70936e1b92a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09e1c4ab-308e-4426-bbaf-65344b43f580"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f0707ff-3fc3-499d-a0b0-41734530415b"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c7c0671-13cd-421f-92e3-5284887f1124"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ab0978d-7561-4fa1-bede-0d0d15085bf3"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b562e487-5795-488c-8b38-ca973707c373"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenSecondaryMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b8f3fd9d-05e7-4e60-91ad-62ec3e704474"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenSecondaryMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c19cb705-202d-45e9-b261-9adddf589612"",
                    ""path"": ""<DualShockGamepad>/touchpadButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenSecondaryMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Always
        m_Always = asset.FindActionMap("Always", throwIfNotFound: true);
        m_Always_Point = m_Always.FindAction("Point", throwIfNotFound: true);
        m_Always_Navigate = m_Always.FindAction("Navigate", throwIfNotFound: true);
        m_Always_Submit = m_Always.FindAction("Submit", throwIfNotFound: true);
        m_Always_Cancel = m_Always.FindAction("Cancel", throwIfNotFound: true);
        m_Always_LeftClick = m_Always.FindAction("LeftClick", throwIfNotFound: true);
        m_Always_Action1 = m_Always.FindAction("Action1", throwIfNotFound: true);
        m_Always_Action2 = m_Always.FindAction("Action2", throwIfNotFound: true);
        m_Always_Action3 = m_Always.FindAction("Action3", throwIfNotFound: true);
        m_Always_Action4 = m_Always.FindAction("Action4", throwIfNotFound: true);
        m_Always_TabLeft = m_Always.FindAction("TabLeft", throwIfNotFound: true);
        m_Always_TabRight = m_Always.FindAction("TabRight", throwIfNotFound: true);
        m_Always_SubTabLeft = m_Always.FindAction("SubTabLeft", throwIfNotFound: true);
        m_Always_SubTabRight = m_Always.FindAction("SubTabRight", throwIfNotFound: true);
        m_Always_MoveLeft = m_Always.FindAction("MoveLeft", throwIfNotFound: true);
        m_Always_MoveRight = m_Always.FindAction("MoveRight", throwIfNotFound: true);
        m_Always_OpenMenu = m_Always.FindAction("OpenMenu", throwIfNotFound: true);
        m_Always_OpenSecondaryMenu = m_Always.FindAction("OpenSecondaryMenu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Always
    private readonly InputActionMap m_Always;
    private IAlwaysActions m_AlwaysActionsCallbackInterface;
    private readonly InputAction m_Always_Point;
    private readonly InputAction m_Always_Navigate;
    private readonly InputAction m_Always_Submit;
    private readonly InputAction m_Always_Cancel;
    private readonly InputAction m_Always_LeftClick;
    private readonly InputAction m_Always_Action1;
    private readonly InputAction m_Always_Action2;
    private readonly InputAction m_Always_Action3;
    private readonly InputAction m_Always_Action4;
    private readonly InputAction m_Always_TabLeft;
    private readonly InputAction m_Always_TabRight;
    private readonly InputAction m_Always_SubTabLeft;
    private readonly InputAction m_Always_SubTabRight;
    private readonly InputAction m_Always_MoveLeft;
    private readonly InputAction m_Always_MoveRight;
    private readonly InputAction m_Always_OpenMenu;
    private readonly InputAction m_Always_OpenSecondaryMenu;
    public struct AlwaysActions
    {
        private @MenuActions m_Wrapper;
        public AlwaysActions(@MenuActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Point => m_Wrapper.m_Always_Point;
        public InputAction @Navigate => m_Wrapper.m_Always_Navigate;
        public InputAction @Submit => m_Wrapper.m_Always_Submit;
        public InputAction @Cancel => m_Wrapper.m_Always_Cancel;
        public InputAction @LeftClick => m_Wrapper.m_Always_LeftClick;
        public InputAction @Action1 => m_Wrapper.m_Always_Action1;
        public InputAction @Action2 => m_Wrapper.m_Always_Action2;
        public InputAction @Action3 => m_Wrapper.m_Always_Action3;
        public InputAction @Action4 => m_Wrapper.m_Always_Action4;
        public InputAction @TabLeft => m_Wrapper.m_Always_TabLeft;
        public InputAction @TabRight => m_Wrapper.m_Always_TabRight;
        public InputAction @SubTabLeft => m_Wrapper.m_Always_SubTabLeft;
        public InputAction @SubTabRight => m_Wrapper.m_Always_SubTabRight;
        public InputAction @MoveLeft => m_Wrapper.m_Always_MoveLeft;
        public InputAction @MoveRight => m_Wrapper.m_Always_MoveRight;
        public InputAction @OpenMenu => m_Wrapper.m_Always_OpenMenu;
        public InputAction @OpenSecondaryMenu => m_Wrapper.m_Always_OpenSecondaryMenu;
        public InputActionMap Get() { return m_Wrapper.m_Always; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AlwaysActions set) { return set.Get(); }
        public void SetCallbacks(IAlwaysActions instance)
        {
            if (m_Wrapper.m_AlwaysActionsCallbackInterface != null)
            {
                @Point.started -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnPoint;
                @Point.performed -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnPoint;
                @Point.canceled -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnPoint;
                @Navigate.started -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnNavigate;
                @Navigate.performed -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnNavigate;
                @Navigate.canceled -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnNavigate;
                @Submit.started -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnSubmit;
                @Submit.performed -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnSubmit;
                @Submit.canceled -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnSubmit;
                @Cancel.started -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnCancel;
                @Cancel.performed -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnCancel;
                @Cancel.canceled -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnCancel;
                @LeftClick.started -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnLeftClick;
                @LeftClick.performed -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnLeftClick;
                @LeftClick.canceled -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnLeftClick;
                @Action1.started -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnAction1;
                @Action1.performed -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnAction1;
                @Action1.canceled -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnAction1;
                @Action2.started -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnAction2;
                @Action2.performed -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnAction2;
                @Action2.canceled -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnAction2;
                @Action3.started -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnAction3;
                @Action3.performed -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnAction3;
                @Action3.canceled -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnAction3;
                @Action4.started -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnAction4;
                @Action4.performed -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnAction4;
                @Action4.canceled -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnAction4;
                @TabLeft.started -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnTabLeft;
                @TabLeft.performed -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnTabLeft;
                @TabLeft.canceled -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnTabLeft;
                @TabRight.started -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnTabRight;
                @TabRight.performed -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnTabRight;
                @TabRight.canceled -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnTabRight;
                @SubTabLeft.started -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnSubTabLeft;
                @SubTabLeft.performed -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnSubTabLeft;
                @SubTabLeft.canceled -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnSubTabLeft;
                @SubTabRight.started -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnSubTabRight;
                @SubTabRight.performed -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnSubTabRight;
                @SubTabRight.canceled -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnSubTabRight;
                @MoveLeft.started -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnMoveLeft;
                @MoveLeft.performed -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnMoveLeft;
                @MoveLeft.canceled -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnMoveLeft;
                @MoveRight.started -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnMoveRight;
                @MoveRight.performed -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnMoveRight;
                @MoveRight.canceled -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnMoveRight;
                @OpenMenu.started -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnOpenMenu;
                @OpenMenu.performed -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnOpenMenu;
                @OpenMenu.canceled -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnOpenMenu;
                @OpenSecondaryMenu.started -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnOpenSecondaryMenu;
                @OpenSecondaryMenu.performed -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnOpenSecondaryMenu;
                @OpenSecondaryMenu.canceled -= m_Wrapper.m_AlwaysActionsCallbackInterface.OnOpenSecondaryMenu;
            }
            m_Wrapper.m_AlwaysActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @Navigate.started += instance.OnNavigate;
                @Navigate.performed += instance.OnNavigate;
                @Navigate.canceled += instance.OnNavigate;
                @Submit.started += instance.OnSubmit;
                @Submit.performed += instance.OnSubmit;
                @Submit.canceled += instance.OnSubmit;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @LeftClick.started += instance.OnLeftClick;
                @LeftClick.performed += instance.OnLeftClick;
                @LeftClick.canceled += instance.OnLeftClick;
                @Action1.started += instance.OnAction1;
                @Action1.performed += instance.OnAction1;
                @Action1.canceled += instance.OnAction1;
                @Action2.started += instance.OnAction2;
                @Action2.performed += instance.OnAction2;
                @Action2.canceled += instance.OnAction2;
                @Action3.started += instance.OnAction3;
                @Action3.performed += instance.OnAction3;
                @Action3.canceled += instance.OnAction3;
                @Action4.started += instance.OnAction4;
                @Action4.performed += instance.OnAction4;
                @Action4.canceled += instance.OnAction4;
                @TabLeft.started += instance.OnTabLeft;
                @TabLeft.performed += instance.OnTabLeft;
                @TabLeft.canceled += instance.OnTabLeft;
                @TabRight.started += instance.OnTabRight;
                @TabRight.performed += instance.OnTabRight;
                @TabRight.canceled += instance.OnTabRight;
                @SubTabLeft.started += instance.OnSubTabLeft;
                @SubTabLeft.performed += instance.OnSubTabLeft;
                @SubTabLeft.canceled += instance.OnSubTabLeft;
                @SubTabRight.started += instance.OnSubTabRight;
                @SubTabRight.performed += instance.OnSubTabRight;
                @SubTabRight.canceled += instance.OnSubTabRight;
                @MoveLeft.started += instance.OnMoveLeft;
                @MoveLeft.performed += instance.OnMoveLeft;
                @MoveLeft.canceled += instance.OnMoveLeft;
                @MoveRight.started += instance.OnMoveRight;
                @MoveRight.performed += instance.OnMoveRight;
                @MoveRight.canceled += instance.OnMoveRight;
                @OpenMenu.started += instance.OnOpenMenu;
                @OpenMenu.performed += instance.OnOpenMenu;
                @OpenMenu.canceled += instance.OnOpenMenu;
                @OpenSecondaryMenu.started += instance.OnOpenSecondaryMenu;
                @OpenSecondaryMenu.performed += instance.OnOpenSecondaryMenu;
                @OpenSecondaryMenu.canceled += instance.OnOpenSecondaryMenu;
            }
        }
    }
    public AlwaysActions @Always => new AlwaysActions(this);
    public interface IAlwaysActions
    {
        void OnPoint(InputAction.CallbackContext context);
        void OnNavigate(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnLeftClick(InputAction.CallbackContext context);
        void OnAction1(InputAction.CallbackContext context);
        void OnAction2(InputAction.CallbackContext context);
        void OnAction3(InputAction.CallbackContext context);
        void OnAction4(InputAction.CallbackContext context);
        void OnTabLeft(InputAction.CallbackContext context);
        void OnTabRight(InputAction.CallbackContext context);
        void OnSubTabLeft(InputAction.CallbackContext context);
        void OnSubTabRight(InputAction.CallbackContext context);
        void OnMoveLeft(InputAction.CallbackContext context);
        void OnMoveRight(InputAction.CallbackContext context);
        void OnOpenMenu(InputAction.CallbackContext context);
        void OnOpenSecondaryMenu(InputAction.CallbackContext context);
    }
}
